// Generated by tools/bank-logos/build.mjs. Logos map only to verified directory IDs.
import type { ImageSourcePropType } from 'react-native'

interface BankLogoAsset {
  readonly source: ImageSourcePropType
  readonly rasterPixels?: number
}

export const bankLogoAssets: Readonly<Partial<Record<string, BankLogoAsset>>> = {
  'abn-amro-nl': {
    source: require('../assets/bank-logos/abn-amro.svg') as ImageSourcePropType,
  },
  'aib-ie': {
    source: require('../assets/bank-logos/aib.svg') as ImageSourcePropType,
  },
  amex: {
    source: require('../assets/bank-logos/american-express.svg') as ImageSourcePropType,
  },
  'banco-bpm': {
    source: require('../assets/bank-logos/banco-bpm.svg') as ImageSourcePropType,
  },
  bancoposta: {
    source: require('../assets/bank-logos/bancoposta.svg') as ImageSourcePropType,
  },
  'bank-austria-at': {
    source: require('../assets/bank-logos/bank-austria.svg') as ImageSourcePropType,
  },
  'bank-of-ireland-ie': {
    source: require('../assets/bank-logos/bank-of-ireland-uk.svg') as ImageSourcePropType,
  },
  'barclays-gb': {
    source: require('../assets/bank-logos/barclays.svg') as ImageSourcePropType,
  },
  'bbva-es': {
    source: require('../assets/bank-logos/bbva.svg') as ImageSourcePropType,
  },
  'berliner-sparkasse-de': {
    source: require('../assets/bank-logos/sparkasse.svg') as ImageSourcePropType,
  },
  bnl: {
    source: require('../assets/bank-logos/bnl.svg') as ImageSourcePropType,
  },
  'bnp-paribas-fortis-be': {
    source: require('../assets/bank-logos/bnp-paribas-fortis.svg') as ImageSourcePropType,
  },
  'bnp-paribas-fr': {
    source: require('../assets/bank-logos/bnpparibas.svg') as ImageSourcePropType,
  },
  'boursobank-fr': {
    source: require('../assets/bank-logos/boursobank.svg') as ImageSourcePropType,
  },
  bper: {
    source: require('../assets/bank-logos/bper.svg') as ImageSourcePropType,
  },
  'bunq-nl': {
    source: require('../assets/bank-logos/bunq.svg') as ImageSourcePropType,
  },
  'caixabank-es': {
    source: require('../assets/bank-logos/caixabank.svg') as ImageSourcePropType,
  },
  'commerzbank-de': {
    source: require('../assets/bank-logos/commerzbank.svg') as ImageSourcePropType,
  },
  credem: {
    source: require('../assets/bank-logos/credem.svg') as ImageSourcePropType,
  },
  'credit-agricole-italia': {
    source: require('../assets/bank-logos/credit-agricole-italia.svg') as ImageSourcePropType,
  },
  'danske-bank-dk': {
    source: require('../assets/bank-logos/danske-bank.svg') as ImageSourcePropType,
  },
  'danske-bank-fi': {
    source: require('../assets/bank-logos/danske-bank-fin.svg') as ImageSourcePropType,
  },
  'deutsche-bank-de': {
    source: require('../assets/bank-logos/deutschebank.svg') as ImageSourcePropType,
  },
  'erste-bank-at': {
    source: require('../assets/bank-logos/erste-bank.svg') as ImageSourcePropType,
  },
  fineco: {
    source: require('../assets/bank-logos/fineco.svg') as ImageSourcePropType,
  },
  'hsbc-gb': {
    source: require('../assets/bank-logos/hsbc.svg') as ImageSourcePropType,
  },
  ing: {
    source: require('../assets/bank-logos/ing.svg') as ImageSourcePropType,
  },
  'ing-de': {
    source: require('../assets/bank-logos/ing.svg') as ImageSourcePropType,
  },
  'ing-nl': {
    source: require('../assets/bank-logos/ing.svg') as ImageSourcePropType,
  },
  'intesa-sanpaolo': {
    source: require('../assets/bank-logos/intesa-sanpaolo.svg') as ImageSourcePropType,
  },
  'kbc-be': {
    source: require('../assets/bank-logos/kbc.svg') as ImageSourcePropType,
  },
  'la-banque-postale-fr': {
    source: require('../assets/bank-logos/la-banque-postale.svg') as ImageSourcePropType,
  },
  'lloyds-gb': {
    source: require('../assets/bank-logos/lloydsbank.svg') as ImageSourcePropType,
  },
  mediolanum: {
    source: require('../assets/bank-logos/mediolanum.svg') as ImageSourcePropType,
  },
  'monte-paschi-siena': {
    source: require('../assets/bank-logos/monte-paschi-siena.svg') as ImageSourcePropType,
    rasterPixels: 136,
  },
  'monzo-gb': {
    source: require('../assets/bank-logos/monzo.svg') as ImageSourcePropType,
  },
  n26: {
    source: require('../assets/bank-logos/n26.svg') as ImageSourcePropType,
  },
  'n26-de': {
    source: require('../assets/bank-logos/n26.svg') as ImageSourcePropType,
  },
  'natwest-gb': {
    source: require('../assets/bank-logos/natwest.svg') as ImageSourcePropType,
  },
  'nordea-dk': {
    source: require('../assets/bank-logos/nordea.svg') as ImageSourcePropType,
  },
  'nordea-fi': {
    source: require('../assets/bank-logos/nordea.svg') as ImageSourcePropType,
  },
  'nordea-no': {
    source: require('../assets/bank-logos/nordea.svg') as ImageSourcePropType,
  },
  postepay: {
    source: require('../assets/bank-logos/postepay.svg') as ImageSourcePropType,
  },
  'rabobank-nl': {
    source: require('../assets/bank-logos/rabobank.svg') as ImageSourcePropType,
  },
  revolut: {
    source: require('../assets/bank-logos/revolut.svg') as ImageSourcePropType,
  },
  'sabadell-es': {
    source: require('../assets/bank-logos/banco-de-sabadell.svg') as ImageSourcePropType,
  },
  'santander-es': {
    source: require('../assets/bank-logos/santanderbank.svg') as ImageSourcePropType,
  },
  satispay: {
    source: require('../assets/bank-logos/satispay.svg') as ImageSourcePropType,
  },
  'seb-se': {
    source: require('../assets/bank-logos/seb.svg') as ImageSourcePropType,
  },
  'societe-generale-fr': {
    source: require('../assets/bank-logos/societegenerale.svg') as ImageSourcePropType,
  },
  'starling-gb': {
    source: require('../assets/bank-logos/starlingbank.svg') as ImageSourcePropType,
  },
  'swedbank-se': {
    source: require('../assets/bank-logos/swedbank.svg') as ImageSourcePropType,
    rasterPixels: 136,
  },
  'ubs-ch': {
    source: require('../assets/bank-logos/ubs.svg') as ImageSourcePropType,
  },
  unicredit: {
    source: require('../assets/bank-logos/unicredit.svg') as ImageSourcePropType,
  },
  widiba: {
    source: require('../assets/bank-logos/widiba.svg') as ImageSourcePropType,
  },
}
