// Generated by tools/bank-logos/build.mjs. Logos map only to verified directory IDs.
import type { ImageSourcePropType } from 'react-native'

interface BankLogoAsset {
  readonly source: ImageSourcePropType
  readonly rasterPixels?: number
}

export const bankLogoAssets: Readonly<Partial<Record<string, BankLogoAsset>>> = {
  'abn-amro-nl': {
    source: require('../assets/bank-logos/abn-amro.png') as ImageSourcePropType,
  },
  'aib-ie': {
    source: require('../assets/bank-logos/aib.png') as ImageSourcePropType,
  },
  amex: {
    source: require('../assets/bank-logos/american-express.png') as ImageSourcePropType,
  },
  'banco-bpm': {
    source: require('../assets/bank-logos/banco-bpm.png') as ImageSourcePropType,
  },
  bancoposta: {
    source: require('../assets/bank-logos/bancoposta.png') as ImageSourcePropType,
  },
  'bank-austria-at': {
    source: require('../assets/bank-logos/bank-austria.png') as ImageSourcePropType,
  },
  'bank-of-ireland-ie': {
    source: require('../assets/bank-logos/bank-of-ireland-uk.png') as ImageSourcePropType,
  },
  'barclays-gb': {
    source: require('../assets/bank-logos/barclays.png') as ImageSourcePropType,
  },
  'bbva-es': {
    source: require('../assets/bank-logos/bbva.png') as ImageSourcePropType,
  },
  'berliner-sparkasse-de': {
    source: require('../assets/bank-logos/sparkasse.png') as ImageSourcePropType,
  },
  bnl: {
    source: require('../assets/bank-logos/bnl.png') as ImageSourcePropType,
  },
  'bnp-paribas-fortis-be': {
    source: require('../assets/bank-logos/bnp-paribas-fortis.png') as ImageSourcePropType,
  },
  'bnp-paribas-fr': {
    source: require('../assets/bank-logos/bnpparibas.png') as ImageSourcePropType,
  },
  'boursobank-fr': {
    source: require('../assets/bank-logos/boursobank.png') as ImageSourcePropType,
  },
  bper: {
    source: require('../assets/bank-logos/bper.png') as ImageSourcePropType,
  },
  'bunq-nl': {
    source: require('../assets/bank-logos/bunq.png') as ImageSourcePropType,
  },
  'caixabank-es': {
    source: require('../assets/bank-logos/caixabank.png') as ImageSourcePropType,
  },
  'commerzbank-de': {
    source: require('../assets/bank-logos/commerzbank.png') as ImageSourcePropType,
  },
  credem: {
    source: require('../assets/bank-logos/credem.png') as ImageSourcePropType,
  },
  'credit-agricole-italia': {
    source: require('../assets/bank-logos/credit-agricole-italia.png') as ImageSourcePropType,
  },
  'danske-bank-dk': {
    source: require('../assets/bank-logos/danske-bank.png') as ImageSourcePropType,
  },
  'danske-bank-fi': {
    source: require('../assets/bank-logos/danske-bank-fin.png') as ImageSourcePropType,
  },
  'deutsche-bank-de': {
    source: require('../assets/bank-logos/deutschebank.png') as ImageSourcePropType,
  },
  'erste-bank-at': {
    source: require('../assets/bank-logos/erste-bank.png') as ImageSourcePropType,
  },
  fineco: {
    source: require('../assets/bank-logos/fineco.png') as ImageSourcePropType,
  },
  'hsbc-gb': {
    source: require('../assets/bank-logos/hsbc.png') as ImageSourcePropType,
  },
  ing: {
    source: require('../assets/bank-logos/ing.png') as ImageSourcePropType,
  },
  'ing-de': {
    source: require('../assets/bank-logos/ing.png') as ImageSourcePropType,
  },
  'ing-nl': {
    source: require('../assets/bank-logos/ing.png') as ImageSourcePropType,
  },
  'intesa-sanpaolo': {
    source: require('../assets/bank-logos/intesa-sanpaolo.png') as ImageSourcePropType,
  },
  'kbc-be': {
    source: require('../assets/bank-logos/kbc.png') as ImageSourcePropType,
  },
  'la-banque-postale-fr': {
    source: require('../assets/bank-logos/la-banque-postale.png') as ImageSourcePropType,
  },
  'lloyds-gb': {
    source: require('../assets/bank-logos/lloydsbank.png') as ImageSourcePropType,
  },
  mediolanum: {
    source: require('../assets/bank-logos/mediolanum.png') as ImageSourcePropType,
  },
  'monte-paschi-siena': {
    source: require('../assets/bank-logos/monte-paschi-siena.png') as ImageSourcePropType,
    rasterPixels: 136,
  },
  'monzo-gb': {
    source: require('../assets/bank-logos/monzo.png') as ImageSourcePropType,
  },
  n26: {
    source: require('../assets/bank-logos/n26.png') as ImageSourcePropType,
  },
  'n26-de': {
    source: require('../assets/bank-logos/n26.png') as ImageSourcePropType,
  },
  'natwest-gb': {
    source: require('../assets/bank-logos/natwest.png') as ImageSourcePropType,
  },
  'nordea-dk': {
    source: require('../assets/bank-logos/nordea.png') as ImageSourcePropType,
  },
  'nordea-fi': {
    source: require('../assets/bank-logos/nordea.png') as ImageSourcePropType,
  },
  'nordea-no': {
    source: require('../assets/bank-logos/nordea.png') as ImageSourcePropType,
  },
  postepay: {
    source: require('../assets/bank-logos/postepay.png') as ImageSourcePropType,
  },
  'rabobank-nl': {
    source: require('../assets/bank-logos/rabobank.png') as ImageSourcePropType,
  },
  revolut: {
    source: require('../assets/bank-logos/revolut.png') as ImageSourcePropType,
  },
  'sabadell-es': {
    source: require('../assets/bank-logos/banco-de-sabadell.png') as ImageSourcePropType,
  },
  'santander-es': {
    source: require('../assets/bank-logos/santanderbank.png') as ImageSourcePropType,
  },
  satispay: {
    source: require('../assets/bank-logos/satispay.png') as ImageSourcePropType,
  },
  'seb-se': {
    source: require('../assets/bank-logos/seb.png') as ImageSourcePropType,
  },
  'societe-generale-fr': {
    source: require('../assets/bank-logos/societegenerale.png') as ImageSourcePropType,
  },
  'starling-gb': {
    source: require('../assets/bank-logos/starlingbank.png') as ImageSourcePropType,
  },
  'swedbank-se': {
    source: require('../assets/bank-logos/swedbank.png') as ImageSourcePropType,
    rasterPixels: 136,
  },
  'ubs-ch': {
    source: require('../assets/bank-logos/ubs.png') as ImageSourcePropType,
  },
  unicredit: {
    source: require('../assets/bank-logos/unicredit.png') as ImageSourcePropType,
  },
  widiba: {
    source: require('../assets/bank-logos/widiba.png') as ImageSourcePropType,
  },
}
