export const meta = {
  name: 'lilleri-brand-explore',
  description: 'Explore three logo directions, colour territories and typography for Lilleri with rendered previews',
  phases: [{ title: 'Explore' }],
}

const TOOLS = '/home/user/Lilleri/tools/brand-render' // set to the absolute path of tools/brand-render (pnpm install there first)
const CONTEXT = `You are part of a top-tier branding studio working on LILLERI, a consumer fintech (Personal Finance Management) brand born in Italy and built to scale across Europe. Today is 2026-10-02. "Lilleri" is Tuscan colloquial Italian for "money" (proverb: "senza lilleri non si lallera"). Product promise: you connect your accounts once and your finances organise themselves (automatic reconciliation, personal AI categorisation, a Review Inbox that only shows what needs attention). The brand must feel: calm, intelligent, trustworthy, light, premium-but-warm, Italian-but-international. It must NOT feel: childish, meme-like, corporate, bank-like, cold, technical, cheap, crypto-bro, neon-fintech cliché, gaming. Avoid clichés: € symbols, coins, rising charts, wallets, credit cards, piggy banks, shields, padlocks, generic rounded-square letter icons on blue/green/purple.

READ FIRST (Read tool): /home/user/Lilleri/docs/brand/brand-strategy.md, /home/user/Lilleri/docs/brand/messaging-framework.md, /home/user/Lilleri/docs/brand/naming-analysis.md, /home/user/Lilleri/docs/research/brand-competitor-analysis.md (palette/shape landscape, white-space opportunities, clichés), and /home/user/Lilleri/docs/research/raw/typography-options.md (skim the recommendation sections).

RENDERING TOOLKIT (use it; judges will look at the PNGs): in ${TOOLS} run with node:
- node ${TOOLS}/render.mjs <in.svg> <out.png> [--width N] [--bg #hex] — render any SVG (fonts available by font-family name: "Geist", "GeistMono", "Inter", "Newsreader", "Manrope", "PlusJakartaSans", "InstrumentSans"; use font-weight 100-900; text must be in <text> elements — if you want a final wordmark you may ALSO convert text to paths by hand-drawing letterforms, but a text-based wordmark rendered in a chosen font is acceptable at this stage).
- node ${TOOLS}/icon-sheet.mjs <icon.svg> <out.png> --title "..." — renders a square icon at 256→16 px on light/dark backgrounds, 1:1 pixels, to judge legibility at small sizes.
- node ${TOOLS}/shelf.mjs <icon.svg> <out.png> [--seed N] — places the icon among 29 generic finance-app icons (recognition test).
- node ${TOOLS}/contrast.mjs "#fg" "#bg" or node ${TOOLS}/contrast.mjs palette.json — WCAG contrast.
- node ${TOOLS}/palette-sheet.mjs palette.json out.png — swatches + mock home screen in light and dark.
After rendering, LOOK at every PNG with the Read tool (it shows images) and iterate at least twice: critique what you see at 16/24/32 px and in the shelf test, fix the SVG, re-render. SVG rules: declare viewBox; use only plain shapes/paths/text (no filters, no external refs, no CSS classes); keep geometry on a clean grid; avoid thin strokes below 1/24 of the icon size.

OUTPUT RULES: Write documents in English (brand copy examples may be Italian). Save SVG sources and PNG renders under /home/user/Lilleri/packages/brand/explorations/<direction>/ (create directories with mkdir -p). Do not modify files outside your own direction/territory folder and your own doc. Never copy a competitor's logo; describe similarity risks honestly.`

const LOGO_SCHEMA = {
  type: 'object',
  properties: {
    direction: { type: 'string' },
    concept: { type: 'string' },
    files: { type: 'array', items: { type: 'string' } },
    self_assessment: { type: 'object', properties: { memorability: { type: 'number' }, scalability: { type: 'number' }, small_size_legibility: { type: 'number' }, store_recognisability: { type: 'number' }, dark_light: { type: 'number' }, originality: { type: 'number' }, competitor_similarity_risk: { type: 'string' } }, required: ['memorability', 'scalability', 'small_size_legibility', 'store_recognisability', 'dark_light', 'originality', 'competitor_similarity_risk'] },
    strengths: { type: 'array', items: { type: 'string' } },
    weaknesses: { type: 'array', items: { type: 'string' } },
  },
  required: ['direction', 'concept', 'files', 'self_assessment', 'strengths', 'weaknesses'],
}
const GENERIC_SCHEMA = { type: 'object', properties: { files: { type: 'array', items: { type: 'string' } }, summary: { type: 'string' }, recommendation: { type: 'string' } }, required: ['files', 'summary', 'recommendation'] }

const DIRECTIONS = [
  { key: 'a', name: 'Direction A — "Settling into order"', brief: `An abstract mark expressing the product truth: scattered things settling into order by themselves. Explore marks built from 2-4 simple elements (strokes, pebbles, bars, dots) where one element is "out of place" and the composition reads as calm resolution: e.g. a stack of rounded bars where the top one is nudged into alignment; three pebbles settling; a short "tick-less" gesture of two strokes meeting. Must read as one memorable silhouette at 16 px. No charts, no arrows pointing up.` },
  { key: 'b', name: 'Direction B — "The double l" letterform', brief: `A letterform-based mark derived from the two "l"s in Lilleri (the word's most distinctive visual feature) — e.g. two tall rounded strokes of different heights forming a quiet, friendly, slightly architectural monogram; or "li" as a ligature where the dot of the i becomes the brand's signature dot. Consider negative space, a single rounded terminal detail that carries into the wordmark, and how the symbol survives as a 16 px favicon. Must not resemble the N26 "26", the Lydia "L", the Lili (US) wordmark, or a generic rounded square with an "L". Also design the wordmark "lilleri" or "Lilleri" (choose and justify the case) so that symbol and wordmark share the same stroke logic.` },
  { key: 'c', name: 'Direction C — "Lillero" token / warm object', brief: `A friendly, tactile object-mark that nods to the Tuscan word for money without using a coin or € sign: e.g. a single soft "lillero" — a rounded squircle/pebble with one subtle cut or notch that makes it unmistakable; or a pair of nested rounded shapes (a thing inside a thing: your money, held). Explore a warm, matte, almost ceramic feel (think Italian design objects, not fintech gloss), and a single signature colour on a paper-like ground. Must still work in pure monochrome and as a 1-colour favicon.` },
]

phase('Explore')
const logos = DIRECTIONS.map(d => () => agent(`${CONTEXT}\n\nYOUR TASK: ${d.name}. ${d.brief}\n\nDeliverables (all under /home/user/Lilleri/packages/brand/explorations/direction-${d.key}/): symbol.svg (viewBox 0 0 1024 1024, transparent background), app-icon.svg (1024 viewBox, WITH background, iOS-style — no rounded corners needed, the OS masks it), wordmark.svg, lockup-horizontal.svg, symbol-mono.svg (single colour #000), symbol-dark.svg (for dark backgrounds), plus renders: symbol@256.png, wordmark.png, lockup.png, icon-sheet.png, shelf.png (run shelf twice with seeds 3 and 11), dark-lockup.png. Then write /home/user/Lilleri/docs/brand/explorations/logo-direction-${d.key}.md covering: concept; meaning; construction notes (grid, proportions, stroke, radii); colour used (one signature colour + neutral, with hex and WCAG contrast against white and against the paper tone you choose); strengths; weaknesses; memorability; scalability; App Store recognisability (describe what you saw in the shelf test); legibility at 16/24/32; dark/light behaviour; monochrome behaviour; similarity risks vs Revolut, N26, Klarna, Satispay, Wise, Curve, Monzo, Lydia, Lili, Emma, Monarch, Copilot, YNAB; what a human designer should refine. Include the image file list with relative paths. Iterate at least twice based on what you SEE in the renders before finalising.`, { label: `logo:${d.key}`, phase: 'Explore', schema: LOGO_SCHEMA }))

const colour = () => agent(`${CONTEXT}\n\nYOUR TASK: Colour system exploration (senior brand designer + accessibility expert). Build THREE distinct colour territories for Lilleri, deliberately avoiding "blue = bank", "green = money", "purple = AI" as the signature (they may appear only as semantic/accent colours): T1 "Warm paper & terracotta" (paper-like warm neutrals + a terracotta/clay signature), T2 "Olive & ink" (sage/olive signature on warm neutrals, ink text), T3 one more original territory you argue for (e.g. deep wine/plum, ochre/saffron, or a desaturated teal-slate — justify with the landscape map in the competitor analysis). For EACH territory produce a palette JSON at /home/user/Lilleri/packages/brand/explorations/colour/t<N>.json with name, light and dark objects containing: background, surface, surfaceElevated, textPrimary, textSecondary, textTertiary, border, primary, onPrimary, secondary, accent, success, warning, danger, info, plus "positive"/"negative" amount colours that are NOT the only cue (we also use +/- signs and labels), and a "chart" array of 6 categorical colours. Run node ${TOOLS}/contrast.mjs on each JSON and node ${TOOLS}/palette-sheet.mjs to render /home/user/Lilleri/packages/brand/explorations/colour/t<N>.png; LOOK at each render and fix any failing contrast (text roles must reach WCAG AA 4.5:1 on background and surface; large amounts AA at least; borders are decorative). Then write /home/user/Lilleri/docs/brand/explorations/colour-territories.md: for each territory — rationale, psychology (trust, calm, clarity, technology, simplicity; not anxiety), nearest competitors and distance from them, accessibility table, dark-mode behaviour, how gains/losses are communicated without relying on red/green only, risks (dated in 2 years? too "lifestyle"? too "ceramic"? prints badly?), and a recommendation with a proposed primary territory and an alternative. Return the files and recommendation.`, { label: 'colour-territories', phase: 'Explore', schema: GENERIC_SCHEMA })

const type = () => agent(`${CONTEXT}\n\nYOUR TASK: Typography decision (type designer + product designer). Candidate fonts available to the renderer: Geist (variable), Inter (variable), Manrope, PlusJakartaSans, InstrumentSans, Newsreader (serif display), GeistMono. (1) Render specimens to /home/user/Lilleri/packages/brand/explorations/type/: for each sans candidate, an SVG+PNG showing: "€ 12.438,72", "-€ 1.234,56", "+€ 2.350,00", "12.438,72 €", "1 I l | 0 O", "€ £ $ CHF ¥ %", Italian text with diacritics "Perché è così? Più chiarezza, meno ansia — città, può, già", a mock transaction row at 16 px and a large amount at 40 px with tabular numerals (font-variant-numeric="tabular-nums"), both in light and dark. Also a specimen pairing Newsreader (display headlines) with the leading sans, and a "lilleri" wordmark test in 3 weights and 2 cases. LOOK at the renders. (2) Decide: Primary typeface (licence must be free for app+web; verify OFL from the raw typography doc), optional Display typeface (only if it adds real brand value), whether a mono/data face is needed (likely only for IBAN/codes). (3) Write /home/user/Lilleri/docs/brand/explorations/typography-decision.md with: comparison table (legibility, numerals/tnum, currency glyphs, 1/I/l and 0/O distinguishability, diacritics, weights, variable support, Expo/web availability via npm, file size, licence, "used by competitor" risk), the decision with rationale, the type scale (Display, H1, H2, H3, Title, Body, Body Small, Label, Caption, Amount Large, Amount Medium) with size/weight/line-height/letter-spacing for mobile and web, number & currency formatting rules for it-IT and other EU locales (run node -e with Intl.NumberFormat to show actual outputs for it-IT, de-DE, fr-FR, es-ES, en-GB for 12438.72 EUR and -1234.56; decide symbol placement and document that Hermes may lack some Intl features), accessibility rules (dynamic type, minimum sizes), and misuse rules. Return files and recommendation.`, { label: 'typography', phase: 'Explore', schema: GENERIC_SCHEMA })

const results = await parallel([...logos, colour, type])
return { results: results.filter(Boolean) }
