import crypto from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { Resvg } from '../brand-render/node_modules/@resvg/resvg-js/index.js'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..')
const directory = path.join(root, 'apps/mobile/assets/bank-logos')
const manifest = JSON.parse(fs.readFileSync(path.join(directory, 'sources.json'), 'utf8'))
const ids = new Set()
const assets = []

for (const entry of manifest.entries) {
  if (!/^[a-z0-9-]+$/.test(entry.key)) throw new Error('Invalid local logo key')
  const svg = fs.readFileSync(path.join(directory, `${entry.key}.svg`), 'utf8')
  if (crypto.createHash('sha256').update(svg).digest('hex') !== entry.sha256)
    throw new Error(`Source checksum changed: ${entry.key}`)
  if (/<(?:script|foreignObject)\b|\bon[a-z]+\s*=/i.test(svg))
    throw new Error(`Active SVG content: ${entry.key}`)
  for (const match of svg.matchAll(/(?:href|xlink:href)\s*=\s*(["'])(.*?)\1/gis)) {
    if (!match[2].startsWith('#') && !/^data:image\/png;base64,[A-Za-z0-9+/=\s]+$/.test(match[2]))
      throw new Error(`External logo resource: ${entry.key}`)
  }
  for (const match of svg.matchAll(/url\(\s*["']?([^\s)'" ]+)/gi))
    if (!match[1].startsWith('#')) throw new Error(`External logo style: ${entry.key}`)
  if (/<image\b/i.test(svg) && !entry.rasterPixels)
    throw new Error(`Embedded raster requires a resolution limit: ${entry.key}`)
  const rasterWidth = entry.rasterPixels ?? 256
  if (!Number.isInteger(rasterWidth) || rasterWidth < 64 || rasterWidth > 2048)
    throw new Error(`Invalid raster resolution: ${entry.key}`)
  const png = new Resvg(svg, { fitTo: { mode: 'width', value: rasterWidth } }).render().asPng()
  fs.writeFileSync(path.join(directory, `${entry.key}.png`), png)
  for (const id of entry.institutionIds) {
    if (!/^[a-z0-9-]+$/.test(id) || ids.has(id)) throw new Error(`Duplicate/invalid service: ${id}`)
    ids.add(id)
    assets.push({ id, key: entry.key, rasterPixels: entry.rasterPixels })
  }
}

for (const [file, extension] of [
  ['bank-logo-assets.ts', 'png'],
  ['bank-logo-assets.web.ts', 'svg'],
]) {
  const lines = [
    '// Generated by tools/bank-logos/build.mjs. Logos map only to verified directory IDs.',
    "import type { ImageSourcePropType } from 'react-native'",
    '',
    'interface BankLogoAsset {',
    '  readonly source: ImageSourcePropType',
    '  readonly rasterPixels?: number',
    '}',
    '',
    'export const bankLogoAssets: Readonly<Partial<Record<string, BankLogoAsset>>> = {',
  ]
  for (const { id, key, rasterPixels } of assets.sort((a, b) => a.id.localeCompare(b.id))) {
    lines.push(
      `  '${id}': {`,
      `    source: require('../assets/bank-logos/${key}.${extension}') as ImageSourcePropType,`,
      ...(rasterPixels ? [`    rasterPixels: ${rasterPixels},`] : []),
      '  },',
    )
  }
  lines.push('}', '')
  fs.writeFileSync(path.join(root, 'apps/mobile/src', file), lines.join('\n'))
}
console.log(`Bundled ${manifest.entries.length} original logos for ${ids.size} directory services.`)
